import Room_1 from '../../images/Room_1.jpg';

export const BreadcrumbProps = {
    img: Room_1,
    alt: 'Image',
    title: 'Devsthali Celebration',
    path: [
        {
            name: 'Events',
            url: '/events'
        },
    ]
};

export const eventObj = [
    {
        lightBg: true,
        primary: false,
        imgStart: '', 
        lightTopLine: false, 
        lightTextDesc: false, 
        buttonLabel: 'Book Now', 
        headline: 'Destination Wedding in Corbett',
        description: 'Whether you are organizing a destination wedding, or attending one, we at Devsthali Brar Resort, is ready to create your dream a reality as per your dream or expectations. Destination weddings are the latest buzz in India. We have expertise in Destination wedding at Jim Corbett and our team of experts who take care of your start to end requirements to makes your wedding a perfect event of your life. Make your Special Moment an Unforgettable Celebration.',
        lightText: false, 
        topLine: '',
        img: Room_1,
        alt: 'Image',
        start: '',
        link: '/rooms'
    },
    {
        lightBg: true,
        primary: false,
        imgStart: 'start', 
        lightTopLine: false, 
        lightTextDesc: false, 
        buttonLabel: 'Book Now', 
        description: 'We host meetings for various companies from various sectors as per their requirements in our resort.  Companies come together to discuss or exchange information from many regions, meetings may be seen as a small-scale conference by others. They can vary in size from only a small group of senior executives to larger gatherings like annual shareholder meetings.', 
        headline: 'Meetings', 
        lightText: false, 
        topLine: '',
        img: Room_1,
        alt: 'Image',
        start: '',
        link: '/rooms'
    },
    {
        lightBg: true,
        primary: false,
        imgStart: '', 
        lightTopLine: false, 
        lightTextDesc: false, 
        buttonLabel: 'Book Now', 
        description: 'We are one of preferred resort in Jim Corbett for Incentive Tours. Incentives tours are probably the most fun part of the MICE segment. Our main aim is to make their stay exciting and which may appear to have little or no connection to business. In this context, the goal of an incentive tours is to thank people for their great performance, boost morale, or increase employee loyalty.', 
        headline: 'Incentives', 
        lightText: false, 
        topLine: '',
        img: Room_1,
        alt: 'Image',
        start: '',
        link: '/rooms'
    },
    {
        lightBg: true,
        primary: false,
        imgStart: 'start', 
        lightTopLine: false, 
        lightTextDesc: false, 
        buttonLabel: 'Book Now', 
        description: 'The purpose of conferences varies, but usually, they’re meant to address and find solutions to challenges in a business or industry. Sharing new insights and research is a big part of that. So are networking and team-building activities. An occasion where the main activity of the attendees is to attend various types of sessions, participates in meetings/discussions, socialise, or attend other organised events.', 
        headline: 'Conferences', 
        lightText: false, 
        topLine: '',
        img: Room_1,
        alt: 'Image',
        start: '',
        link: '/rooms'
    },
    {
        lightBg: true,
        primary: false,
        imgStart: '', 
        lightTopLine: false, 
        lightTextDesc: false, 
        buttonLabel: 'Book Now', 
        description: 'TOne of the most personal and important features of your wedding planning process will be choosing your wedding party. Your wedding/pre-wedding event may vary depending on your personal likings, religious practices, and cultural traditions.  We host Pre-wedding to Wedding parties include everything from the engagement party to the rehearsal dinner.', 
        headline: 'Wedding Anniversary', 
        lightText: false, 
        topLine: '',
        img: Room_1,
        alt: 'Image',
        start: '',
        link: '/rooms'
    },
    {
        lightBg: true,
        primary: false,
        imgStart: 'start', 
        lightTopLine: false, 
        lightTextDesc: false, 
        buttonLabel: 'Book Now', 
        headline: 'Graduation Parties',
        description: 'Completion of Graduation is a dream of very one.  Graduation is millstone for the every student from various streams. We make their graduation day by hosting Graduation Party for them.  Graduation party themes add a fun touch to your event, as well as help guide you’re decorating and menu planning.', 
        lightText: false, 
        topLine: '',
        img: Room_1,
        alt: 'Image',
        start: '',
        link: '/rooms'
    },
    {
        lightBg: true,
        primary: false,
        imgStart: '', 
        lightTopLine: false, 
        lightTextDesc: false, 
        buttonLabel: 'Book Now', 
        headline: 'Retirement Parties',
        description: 'We host retirement parties for our clients. We plan their retirement parties make their retirement day memorable. We have verity of foods in menu to fulfil their food needs at our resort in Jim Corbett.',
        lightText: false, 
        topLine: '',
        img: Room_1,
        alt: 'Image',
        start: '',
        link: '/rooms'
    },
    {
        lightBg: true,
        primary: false,
        imgStart: 'start', 
        lightTopLine: false, 
        lightTextDesc: false, 
        buttonLabel: 'Book Now', 
        headline: 'Baby Shower Parties', 
        description: 'Make your baby shower extra special with our baby shower party at Jim Corbett, Devsthali Brar Resort. Your baby is almost here and your loved ones are ready to shower them with gifts and good wishes. Sure taking your baby shower virtual is a big shift from what you had planned, but dont let that stop you.',
        lightText: false, 
        topLine: '',
        img: Room_1,
        alt: 'Image',
        start: '',
        link: '/rooms'
    },
    {
        lightBg: true,
        primary: false,
        imgStart: '', 
        lightTopLine: false, 
        lightTextDesc: false, 
        buttonLabel: 'Book Now', 
        headline: 'Bachelorette Parties', 
        description: 'Are you ready for an unforgettable party experience in before getting married?  We are here in Jim Corbett to give you a memorable bachelorette party in which you will be involved with your close friends and relative.  And when we speak of parties, it can never be complete without proper bachelorette party. Check out the best bachelorette party decoration and delicious food with us.', 
        lightText: false, 
        topLine: '',
        img: Room_1,
        alt: 'Image',
        start: '',
        link: '/rooms'
    }
];
